#+latex_header: \usepackage{naive-ebnf}

* Overview
$E :=$ The set of possible s-expressions.
$\Omega :=$ The set of possible elisp values.[fn:: Technically, $\Omega = E$, but we will notate them differently for clarity]
$\operatorname{Sig} :=$ The set of signals an expression could produce
$R := \operatorname{return} \Omega \mid \operatorname{signal} \text{Sig}$ The set of results that evaluating an expression can have
Technically, the expression =(push 4 a)= where =a=5= will return the value =(4 . 5)=, but the user probably did not intend to push onto a non-list. Thus, we should introduce a modified notion of what a function can return.
$\overline{R} := \operatorname{undefined} \mid \operatorname{defined} R$

Our end goal is a type checker $\mathcal{C} : E \rightarrow \overline{R}$.
For $\mathcal{C}$ to be "correct", we must have that all possible return values of $e \in E$ are elements of $\mathcal{C}(e)$.
Making a correct type checker is easy. For example, both checkers $\mathcal{C}_{\text{defined}} = e \mapsto \operatorname{defined} R$ and $\mathcal{C}_{\text{undefined}} : e \mapsto \operatorname{undefined}$ are correct type checkers.
Our goal is to find a correct $\mathcal{C}$ while doing two things:
1. Choosing a "reasonable" subset $E_\text{defined} \subseteq E$ to mark as defined
2. Minimizing $\mathcal{C}(e)$ for each $e \in E_\text{defined}$

* Types
$D_T$ is the set of root datatypes, such as numbers, strings, and cons cells. Some datatype, such as cons cells, have arguments. For $D_T$, these arguments have the type $T$. Each argument can be either covariant, contravariant, or isovariant.
$A_T := \left\{ (\text{id}, t) : t \in T \right\}$ is the set of alias types. The identifier is necessary because we want to be able to treat aliases differently from the baseline type. For example, if we were inferring $\text{List}\langle \text{MyAlias} \rangle$ as a $\text{List}\langle T \rangle$, then we would want to get that $T = \text{MyAlias}$, rather than the expansion of $\text{MyAlias}$.
$C_{T,\Delta} := \left( \operatorname{datatype} D_T \mid \operatorname{alias} A_T, \operatorname{bind} (T, \text{var})^\ast, \operatorname{typeof} \text{var}^\ast \right)$.
Let $\phi_{C_{\Delta}} : C_{T,\Delta} \rightarrow \mathcal{P}(R)$ returning the set of values each case represents.
Each type is a union of cases
\begin{align*}
T_\Delta := {C_{T,\Delta}}^{\ast}
\end{align*}
We get the definition
\begin{align*}
\phi_{T_\Delta}(t) : T_\Delta \rightarrow \mathcal{P}(R) = \bigcup_{c \in t} \phi_{C_\Delta}(c)
\end{align*}

A similar notion can be extended to the notion of undefined results: $\overline{T}_\Delta := \operatorname{undefined} \mid \operatorname{defined} T_\Delta$
\begin{align*}
\phi_{\overline{T_\Delta}} : \overline{T_\Delta} \rightarrow \mathcal{P}(\overline{R}) =
\begin{cases} 
\operatorname{defined} \phi_{T_\Delta}(t) & \operatorname{defined} t \\
\operatorname{undefined} & \operatorname{undefined}
\end{cases}
\end{align*}

For $s,t \in T_\Delta$, define $s \le t := \phi_{T_\Delta}(s) \subseteq \phi_{T_\Delta}(t)$.
For $\overline{s},\overline{t} \in \overline{T_\Delta}$, define $\overline{s} \le \overline{t} := \phi_{\overline{T_\Delta}}(\overline{s}) \subseteq \phi_{\overline{T_\Delta}}(\overline{t})$.

* Functions
Let $f : \Omega \rightarrow R$ be an elisp function. An input to this function is the list of values passed to an elisp function, which is why we only need one input value.
We want to define $\widetilde{f} : T_\Delta \rightarrow \overline{T_\Delta}$.
*Correctness property:* $x \in \Omega, t \in T_\Delta, x : t \Longrightarrow f(x) : \widetilde{f}(t)$.
This asserts that the result type of a function will be a superset of the actual results of the function.
Note that all values are elements of the $\text{undefined}$ type.

We can then define the more useful function
\begin{align*}
\widetilde{\overline{f}}(\overline{t_1},...,\overline{t_n}) : \overline{T_\Delta}^\ast \rightarrow \overline{R} := \begin{cases} 
\widetilde{f}(\operatorname{ListType}\langle t_1,...,t_n \rangle) & (\operatorname{defined} t_1,...,\operatorname{defined} t_n) = (\overline{t_1},...,\overline{t_n}) \\
\operatorname{undefined} & \operatorname{undefined} \in \left\{ t_1,...,t_n \right\} \\
\end{cases}
\end{align*}

From now on, I will refer to $T_\Delta$ as $T$ for brevity.


* Matcher types
A match type is something we compare a real type against to figure out generics.
A matcher for generics $a_1,...,a_n$ is a sequence of clauses:
\begin{align*}
M^{a_1,...,a_n} := (C_M^{a_1,...,a_n})^{\ast}
\end{align*}
Each clause is a sequence of match factors, where all factors have to match for the clause to match.
\begin{align*}
C_M^{a^\ast} := (F_M^{a^\ast})^\ast
\end{align*}
\begin{align*}
F_M^{a_1,...,a_n} = \operatorname{datatype} D_{M^{a_1,...,a_n}} \mid \operatorname{alias} A_{M^{a_1,...,a_n}} \mid \operatorname{var} a_i \mid \operatorname{set} (a_i,t)
\end{align*}
The function $\operatorname{M-expand-aliases} : M^{a^\ast} \rightarrow M'^{a^\ast}$ will recursively expand all /root-level/ aliases, where $M'^{a^\ast} = C_M'^{a^\ast}$, $C_M'^{a^\ast} = (F_M'^{a^\ast})^\ast$, and $F_M'^{a^\ast} = \operatorname{datatype} D_{M^{a^\ast}} \mid \operatorname{var} a_i \mid \operatorname{set} (a_i,t)$. Note that the subscript of $D$ is still the standard (not prime) $M^{a^\ast}$, signifying that expanding does not expand the nested aliases. This allows for expanding indirectly recursive types such as $\operatorname{List}$.
Additionally, in both $\operatorname{sub1}$ and $\operatorname{sup1}$, we will store a scoped mapping of all nested subtypes/supertypes currently being evaluated. If we recursively encounter the same subtype/supertype check, it must be because of an indirectly recursive alias. Thus, whatever constraints are required to satisfy the check will be returned by the parent call, so the child (duplicate) call can safely return an empty list of constraints.

There are three types of matching: In subtype matching, we try to find generics which make the type a subtype of the matcher. In supertype matching, we try to make the type a supertype of the matcher. In equality matching, we try to make the type equal to the matcher.

** match-constraints
Matching a types against a match factor results in a list of constraints for our generics, where each constraint looks like:
$Q_{a_1,...,a_n} := \operatorname{Q_\emptyset} \mid \operatorname{Q_{=}} a_i \, T \mid \operatorname{Q_{\le}} a_i \, T \mid \operatorname{Q_{\ge}} a_i \, T$

** Converting constraints to a type
Once we have a collection of constraints ${q_{a_1,...,a_n}}^{\ast} \in {Q_{a_1,...,a_n}}^{\ast}$, we need to determine whether a solution is possible.
Firstly, if $Q_{\text{never} \in }q^{\ast}_{a_1,...,a_n}$, then we can immediately determine that the match is unsatisfiable.
Otherwise, separate by each variable, getting ${q_{a_i}}^{\ast}$.
We will construct a $\text{gle}$, the greatest type which satisfies all $Q_\leq$ and $Q_=$ constraints
\begin{align*}
\operatorname{gle} = \bigcap_{Q_{\le} a_i, t \mid Q_{\le} a_i, t \in q_{a_i}^\ast} t
\end{align*}
Then, we check whether this satisfies the remaining constraints
\begin{align*}
\forall_{Q_{\ge} a_i, t \mid Q_{=} a_i, t \in q_{a_i}^\ast} t \le \text{gle}
\end{align*}
If it does, then $\operatorname{solution}q_{a_i}^\ast = \text{gle}$, and otherwise there is no solution.

** Subtype matching
Notice that
\begin{align*}
\forall_{c_T} \exists_{c_M} c_M \trianglerighteq c_T \Longrightarrow M \trianglerighteq T
\end{align*}
But we get $\not\Longleftarrow$ if $M = \operatorname{nil} \mid \operatorname{cons}\langle X, \operatorname{List} \langle X \rangle \rangle$ and $T = \operatorname{List} \langle X \rangle$
The solution is to do
\begin{align*}
\forall_{c_T} \left( \exists_{c_M} c_M \trianglerighteq c_T \lor M \trianglerighteq \operatorname{expand-alias} c_T \right) \Longrightarrow M \trianglerighteq T
\end{align*}
which is slightly better.

We define
\begin{align*}
\text{sub1}(m_{a^\ast}, t) : M^{a^\ast} \times T \rightarrow Q_{a^\ast}^\ast = \bigcup_{c_T \in t} \text{sub2}(\operatorname{expand-aliases} m_{a^\ast}, c_T)
\end{align*}
The resulting type must satisfy /all/ of the case match constraints, because of the root-level forall statement, hence the union.
\begin{align*}
&\operatorname{sub2}(m, c_T) : M'^{a^\ast} \times C_T \rightarrow Q_{a^\ast}^\ast \\
&= \begin{cases}
\bigcup_{f \in c_M} \operatorname{sub3}(f, c_T) \text{ for the first matching $c_M$} &(2.1)\; \exists_{c_M} c_M \trianglerighteq c_T \\
\operatorname{sub1}(m, \operatorname{expand-alias} c_T) &(2.2)\; m \trianglerighteq \operatorname{expand-alias} c_T \\
\left\{ \operatorname{Q_\emptyset} \right\} &(2.3)\; \text{otherwise}
\end{cases}
\end{align*}
using
\begin{align*}
&\text{sub3}(f, c_T) : F_M'^{a_1,...,a_n} \times C_T \rightarrow Q_{a_1,...,a_n}^\ast  \\
&= \begin{cases} 
\left\{ \operatorname{Q_{\ge}} a_i, c_T \text{ as type} \right\} & f= \operatorname{match} a_i \\
\left\{ \operatorname{Q_\ge} a_i, t \right\} & f= \operatorname{set} (a_i,t) \\
\left\{ \operatorname{Q_{\emptyset}} \right\} & f= \operatorname{datatype} d \text{ and } c_T \text{ is alias} \text{ (defer to 2.2)} \\
\operatorname{sub4}(d, c_T) & f= \operatorname{datatype} d_M \text{ and } c_T = \operatorname{datatype} d_T \\
\left\{ \operatorname{Q_\emptyset} \right\} & f= \operatorname{datatype} d \text{ otherwise} \\
\end{cases}
\end{align*}
using
\begin{align*}
\operatorname{sub4}(d_M, d_T) : D_{M^{a_1,...,a_n}} \times D_T \rightarrow Q_{a^\ast}^\ast
\end{align*}
If $d_M$ and $d_T$ have different underlying datatypes, then return $Q_\emptyset$.
Otherwise, iterate over each (shared) argument. If it is a covariant argument, use $\operatorname{sub1}$. If it is a contravariant argument, use $\operatorname{sup1}$. If it is an isovariant argument, use $\operatorname{iso1}$. Then, union all of the resulting constraints.

*** Note on incompleteness of $\operatorname{sub2}$
In an ideal, world, $(2.1)$ would not just return the first possible constraint, but would instead return the logical "or" of all of the constraints, since only one of them needs to be satisfied. However, I believe that this will rarely be of concern, and would require a more complex representation for constraints. For example, you would need to represent "$a_1$ is $\operatorname{String}$ /or/ $a_2$ is $\operatorname{String}$".

Here is an example of where this would be an issue:
Consider matching $\operatorname{Cons}\langle \operatorname{Vec}\langle \operatorname{Number} \rangle,\; \operatorname{Cons}\langle \operatorname{String},\; \operatorname{Number} \rangle \rangle$ against $\operatorname{Cons}\langle \operatorname{Vec}\langle A \rangle \mid \operatorname{Vec}\langle B \rangle,\; \operatorname{Cons}\langle A,\; B \rangle \rangle$. This is possible with $A=\operatorname{String}$ and $B=\operatorname{Number}$.
Our algorithm will not however find a solution, as for the left side of the cons, it will choose the constraint $Q_= A,\;\operatorname{Number}$, when the constraint $Q_= B,\;\operatorname{Number}$ would have been a valid alternative. The reason for this failure is that it is impossible to represent "either $A=\operatorname{Number}$ or $B=\operatorname{Number}$" as a single constraint. We will just accept that we cannot satisfy this example.

** Supertype Matching
Notice that
\begin{align*}
\forall_{c_M} \exists_{c_T} c_M \trianglelefteq c_T \Longrightarrow M \trianglelefteq T
\end{align*}
We can expand matcher aliases right away without losing anything, so we don't need to do the "fallback" step we had to do for subtype matching.

We define
\begin{align*}
\text{sup1}(m_{a^\ast}, t) : M^{a^\ast} \times T \rightarrow Q_{a^\ast}^\ast = \bigcup_{c_M \in \operatorname{expand-aliases} m_{a^\ast}} \text{sup2}(c_M, t)
\end{align*}
The resulting type must satisfy /all/ of the case match constraints, because of the root-level forall statement, hence the union.
\begin{align*}
&\operatorname{sup2}(c_M, t) : C_M'^{a^\ast} \times T \rightarrow Q_{a^\ast}^\ast \\
&= \begin{cases}
\left\{ Q_{\le} a_i, t \right\} & c_M = \left\{ \operatorname{var} a_i \right\}\\
\bigcup_{f \in c_M} \operatorname{sup3}(f, c_T) \text{ for the first matching $c_T$} &\exists_{c_T} c_M \trianglelefteq c_T \\
\left\{ \operatorname{Q_\emptyset} \right\} &\text{otherwise}
\end{cases}
\end{align*}
using
\begin{align*}
&\text{sup3}(f, c_T) : F_M'^{a_1,...,a_n} \times C_T \rightarrow Q_{a_1,...,a_n}^\ast  \\
&= \begin{cases} 
\left\{ \operatorname{Q_{\le}} a_i, c_T \text{ as type} \right\} & f = \operatorname{match} a_i \\
\left\{ \operatorname{Q_\le} a_i, t \right\} & f = \operatorname{set} (a_i,t) \\
\operatorname{sup1}(d \text{ as } M, \operatorname{expand-alias} a_T) & f = \operatorname{datatype} d \text{ and } c_T = \operatorname{alias} a_T \\
\operatorname{sub4}(d_M, d_T) & f = \operatorname{datatype} d_M \text{ and } c_T = \operatorname{datatype} d_T \\
\left\{ \operatorname{Q_\emptyset} \right\} & f = \operatorname{datatype} d \text{ otherwise} \\
\end{cases}
\end{align*}
using
\begin{align*}
\operatorname{sub4}(d_M, d_T) : D_{M^{a_1,...,a_n}} \times D_T \rightarrow Q_{a^\ast}^\ast
\end{align*}
Same as $\operatorname{sup4}$, but switch the use of $\operatorname{sub1}$ and $\operatorname{sup1}$ for covariant/contravariant arguments.

** Examples
#+begin_src
set-car-to-int(wo:cons<integer, any>) with input type cons<number, number>

sub1(wo:cons<integer, never>  cons<number, number>)
sup1(integer  number) => YES
sup1(never  number) => YES



set-car<A>(wo:cons<A, any>  A) with input type (cons<number, number>  integer)

sub1(wo:cons<A, never>  cons<number, number>)
sup1(A  number) => {A <= number}
sup1(never  number) => YES
sub1(A  integer) => {A >= integer}
we get {A <= number} and {A >= integer} which is satisfiable!!!
#+end_src


