;; -*- lexical-binding: t; -*-

;;; ============================================================
;;; next-error support framework

(et-declare
 (@def next-error-buffer-p (buffer: Buffer &optional avoid-current: Bool extra-test-inclusive: fn? extra-test-exclusive: fn?) Boolean)
 (@def next-error-buffer-on-selected-frame (&optional avoid-current: Bool extra-test-inclusive: fn? extra-test-exclusive: fn?) Buffer?)
 (@def next-error-buffer-unnavigated-current (&optional avoid-current: Bool extra-test-inclusive: fn? extra-test-exclusive: fn?) Buffer?)
 (@def next-error-find-buffer (&optional avoid-current: Bool extra-test-inclusive: fn? extra-test-exclusive: fn?) Buffer)
 (@def next-error (&optional arg: Any reset: Bool) Nil)
 (@def next-error-internal () Nil)
 (@def next-error-quit-window (from-buffer: Buffer? to-buffer: Buffer) Nil)
 (@def next-error-found (&optional from-buffer: Buffer? to-buffer: Buffer?) Nil)
 (@def next-error-select-buffer (buffer: Buffer) Buffer)
 (@def previous-error (&optional n: Integer?) Nil)
 (@def first-error (&optional n: Integer?) Nil)
 (@def next-error-no-select (&optional n: Integer?) Nil)
 (@def next-error-this-buffer-no-select (&optional n: Integer?) Nil)
 (@def previous-error-no-select (&optional n: Integer?) Nil)
 (@def previous-error-this-buffer-no-select (&optional n: Integer?) Nil)
 (@def next-error-follow-minor-mode (&optional arg: Bool) Boolean)
 (@def next-error-follow-mode-post-command-hook () Nil)
 (@def next-error-message-highlight (error-buffer: Buffer) Overlay?)
 (@def recenter-current-error (&optional arg: Any) Nil)
 (@def fundamental-mode () Nil)
 (@def clean-mode () Nil)
 (@def special-mode () Nil)
 (@def newline (&optional arg: Any interactive: Bool) Nil)
 (@def set-hard-newline-properties (from: IntOrMarker to: IntOrMarker) Nil)
 (@def open-line (n: Integer) Nil)
 (@def split-line (&optional arg: String|Bool) Nil)
 (@def make-separator-line (&optional length: Integer?) String)
 (@def delete-indentation (&optional arg: Bool beg: IntOrMarker? end: IntOrMarker?) Nil)
 (@def delete-blank-lines () Nil)
 (@def region-modifiable-p (start: IntOrMarker end: IntOrMarker) Boolean)
 (@def delete-trailing-whitespace (&optional start: IntOrMarker? end: IntOrMarker?) Nil)
 (@def delete-trailing-whitespace-if-possible () Nil)
 (@def delete-trailing-whitespace-mode (&optional arg: Bool) Boolean)
 (@def newline-and-indent (&optional arg: Integer?) Nil)
 (@def reindent-then-newline-and-indent () Nil)
 (@def read-quoted-char (&optional prompt: String?) Integer)
 (@def quoted-insert (arg: Integer) Nil)
 (@def forward-to-indentation (&optional arg: Integer?) Nil)
 (@def backward-to-indentation (&optional arg: Integer?) Nil)
 (@def back-to-indentation () Nil)
 (@def fixup-whitespace () Nil)
 (@def delete-horizontal-space (&optional backward-only: Bool) Nil)
 (@def delete-all-space (&optional backward-only: Bool) Nil)
 (@def just-one-space (&optional n: Integer?) Nil)
 (@def cycle-spacing (&optional n: Any) Nil)
 (@def beginning-of-buffer (&optional arg: Any) Nil)
 (@def end-of-buffer (&optional arg: Any) Nil)
 (@def delete-backward-char (n: Integer &optional killflag: Bool) Nil)
 (@def delete-forward-char (n: Integer &optional killflag: Bool) Nil)
 (@def mark-whole-buffer () Nil)
 (@def goto-line-read-args (&optional relative: Bool) &List)
 (@def goto-line (line: Integer &optional buffer: Buffer? relative: Bool interactive: Bool) Nil)
 (@def goto-line-relative (line: Integer &optional buffer: Buffer? interactive: Bool) Nil)
 (@def count-words-region (start: IntOrMarker? end: IntOrMarker? &optional arg: Bool) Nil|Integer)
 (@def count-words (start: IntOrMarker? end: IntOrMarker? &optional totals: Bool) Nil|Integer)
 (@def what-line () Nil)
 (@def count-lines (start: IntOrMarker end: IntOrMarker &optional ignore-invisible-lines: Bool) Integer)
 (@def what-cursor-position (&optional detail: Bool) Nil)
 (@def read-minibuffer (prompt: String &optional initial-contents: String|Cons<String~Integer>?) Any)
 (@def eval-minibuffer (prompt: String &optional initial-contents: String|Cons<String~Integer>?) Any)
 (@def eval-expression-print-format (value: Any) String?)
 (@def eval-expression-get-print-arguments (prefix-argument: Any) &List)
 (@def eval-expression (exp: Any &optional insert-value: Bool no-truncate: Bool char-print-limit: Any) Any)
 (@def edit-and-eval-command (prompt: String command: Any) Any)
 (@def repeat-complex-command (arg: Integer) Any)
 (@def execute-extended-command-cycle () Never)
 (@def read-extended-command-mode (&optional arg: Bool) Boolean)
 (@def read-extended-command (&optional prompt: String?) String)
 (@def read-extended-command-1 (prompt: String? initial-input: Any) String)
 (@def command-completion-using-modes-p (symbol: NonNilSymbol buffer: Buffer) Boolean)
 (@def command-completion-default-include-p (symbol: NonNilSymbol buffer: Buffer) Boolean)
 (@def command-completion-with-modes-p (modes: &List<Symbol> buffer: Buffer) Boolean)
 (@def command-completion-using-modes-and-keymaps-p (symbol: NonNilSymbol buffer: Buffer) Boolean)
 (@def command-completion-button-p (category: Any buffer: Buffer) Boolean)
 (@def execute-extended-command (prefixarg: Any &optional command-name: String? typed: String?) Nil)
 (@def execute-extended-command-for-buffer (prefixarg: Any &optional command-name: String? typed: String?) Nil)
 (@def command-execute (cmd: NonNilSymbol &optional record-flag: Bool keys: Any special: Bool) Any)
 (@def command-query (command: NonNilSymbol query: String &optional verbose: Bool) Nil)
 (@def minibuffer-history-initialize () Nil)
 ;; Obsolete function retained only for compatibility; behavior is a no-op
 ;; point-motion hook wrapper. The type language has no blocker here, but
 ;; its declared behavior is trivial.
 (@def minibuffer-avoid-prompt (new: Any old: Any) Nil)
 (@def previous-matching-history-element (regexp: String n: Integer) Nil)
 (@def next-matching-history-element (regexp: String n: Integer) Nil)
 (@def minibuffer-default-add-completions () &List<String>)
 (@def minibuffer-history-value () Any)
 (@def goto-history-element (nabs: Integer) Nil)
 (@def next-history-element (n: Integer) Nil)
 (@def previous-history-element (n: Integer) Nil)
 (@def next-line-or-history-element (&optional arg: Integer?) Nil)
 (@def previous-line-or-history-element (&optional arg: Integer?) Nil)
 (@def next-complete-history-element (n: Integer) Nil)
 (@def previous-complete-history-element (n: Integer) Nil)
 (@def minibuffer-prompt-width () Integer)
 (@def minibuffer-history-isearch-setup () Nil)
 (@def minibuffer-history-isearch-end () Nil)
 (@def minibuffer-history-isearch-search () fn<Any~Any>)
 (@def minibuffer-history-isearch-message (&optional c-q-hack: Any ellipsis: Any) Nil)
 (@def minibuffer-history-isearch-wrap () Nil)
 (@def minibuffer-history-isearch-push-state () fn1<Any>)
 (@def minibuffer-history-isearch-pop-state (cmd: Any hist-pos: Integer) Nil)
 (@def minibuffer-error-initialize () Nil)
 (@def minibuffer-error-function (data: Any context: String caller: Symbol?) Any)
 (@def undo (&optional arg: Any) Nil)
 (@def undo-ignore-read-only (&optional arg: Any) Nil)
 (@def buffer-disable-undo (&optional buffer: Buffer?) Nil)
 (@def undo-only (&optional arg: Any) Nil)
 (@def undo-redo (&optional arg: Integer?) Nil)
 (@def undo-more (n: Integer) Nil)
 ;; The undo-list structure mixes markers, integers, cons cells, and
 ;; special tagged forms with value-dependent shapes. The type language
 ;; cannot yet express this heterogeneous, self-describing list format.
 (@def primitive-undo (n: Integer list: Todo) Todo)
 (@def undo-copy-list (list: &List) List)
 (@def undo-copy-list-1 (elt: Any) Any)
 (@def undo-start (&optional beg: Integer? end: Integer?) Any)
 ;; Return value is built from undo-list elements whose heterogeneous
 ;; shape (see `primitive-undo') the type language cannot yet express.
 (@def undo-make-selective-list (start: Integer end: Integer) Todo)
 (@def undo-elt-in-region (undo-elt: Todo start: Integer end: Integer) Boolean)
 (@def undo-elt-crosses-region (undo-elt: Todo start: Integer end: Integer) Boolean)
 (@def undo-adjust-elt (elt: Todo deltas: &List) Todo)
 (@def undo-adjust-beg-end (beg: Integer end: Integer deltas: &List) Cons<Integer~Integer>)
 (@def undo-adjust-pos (pos: Integer deltas: &List &optional use-<: Bool) Integer)
 (@def undo-delta (undo-elt: Todo) Cons<Integer~Integer>)
)

;;; ============================================================
;;; Default undo-boundary addition

(et-declare
 (@def undo-auto-amalgamate () Nil)
 (@def undo-amalgamate-change-group (handle: &List) Nil)
 (@def undo-outer-limit-truncate (size: Integer) Boolean)
 (@def minibuffer-default-add-shell-commands () List<String>)
 (@def read-shell-command (prompt: String &optional initial-contents: String? hist: NonNilSymbol? &rest args: &List) String)
 (@def shell-command-save-pos-or-erase (&optional output-to-current-buffer: Bool) Nil)
 (@def shell-command-set-point-after-cmd (&optional buffer: Buffer?) Nil)
 (@def async-shell-command (command: String &optional output-buffer: Buffer|String? error-buffer: Buffer|String?) Nil|Integer|String)
 (@def shell-command (command: String &optional output-buffer: Any error-buffer: Buffer|String?) Nil|Integer|String)
 (@def file-user-uid () Integer)
 (@def file-group-gid () Integer)
 (@def max-mini-window-lines (&optional frame: Frame?) Number)
 (@def display-message-or-buffer (message: String|Buffer &optional buffer-name: String? action: Any frame: Frame?) String|Window)
 (@def shell-command-sentinel (process: Process signal: String) Nil)
 (@def shell-command-on-region (start: IntOrMarker end: IntOrMarker command: String &optional output-buffer: Any replace: Any error-buffer: Buffer|String? display-error-buffer: Bool region-noncontiguous-p: Bool) Nil|Integer|String)
 (@def shell-command-to-string (command: String) String)
 (@def process-file (program: String &optional infile: String? buffer: Any display: Bool &rest args: &List<String>) Nil|Integer|String)
 (@def start-file-process (name: String buffer: Buffer|String? program: String? &rest program-args: &List<String>) Process)
 (@def process-menu-mode () Nil)
 (@def process-menu-delete-process () Nil)
 (@def process-menu-visit-buffer (button: Any) Nil)
 (@def list-processes (&optional query-only: Bool buffer: Buffer|String?) Nil)
 (@def internal-echo-keystrokes-prefix () String?)
 (@def prefix-command-update () Nil)
 (@def prefix-command-preserve-state () Nil)
 (@def reset-this-command-lengths () Nil)
 (@def universal-argument () Nil)
 (@def universal-argument-more (arg: Any) Nil)
 (@def negative-argument (arg: Any) Nil)
 (@def digit-argument (arg: Any) Nil)
 (@def filter-buffer-substring (beg: IntOrMarker end: IntOrMarker &optional delete: Bool) String)
 (@def kill-new (string: String &optional replace: Bool) Nil)
 (@def kill-append (string: String before-p: Bool) Nil)
 (@def current-kill (n: Integer &optional do-not-move: Bool) String)
 (@def kill-region (beg: IntOrMarker end: IntOrMarker &optional region: Any) Nil)
 (@def copy-region-as-kill (beg: IntOrMarker end: IntOrMarker &optional region: Any) Nil)
 (@def kill-ring-save (beg: IntOrMarker end: IntOrMarker &optional region: Any) Nil)
 (@def region-indistinguishable-p () Boolean)
 (@def indicate-copied-region (&optional message-len: Integer?) Nil)
 (@def append-next-kill (&optional interactive: Bool) Nil)
 (@def squeeze-bidi-context-1 (from: Marker to: Marker category: String replacement: String) Nil)
 (@def squeeze-bidi-context (from: Integer to: Integer?) Nil)
 (@def line-substring-with-bidi-context (start: Integer end: Integer &optional no-properties: Bool) String)
 (@def buffer-substring-with-bidi-context (start: Integer end: Integer &optional no-properties: Bool) String)
 (@def yank-pop (&optional arg: Integer?) Nil)
 (@def yank (&optional arg: Any) Nil)
 (@def rotate-yank-pointer (arg: Integer) String)
 (@def yank-in-context (&optional arg: Any) Nil)
 (@def read-from-kill-ring (prompt: String) String)
 (@def yank-from-kill-ring (string: String &optional arg: Any) Nil)
 (@def kill-forward-chars (arg: Any) Nil)
 (@def kill-backward-chars (arg: Any) Nil)
 (@def backward-delete-char-untabify (arg: Integer &optional killp: Bool) Nil)
 (@def char-uppercase-p (char: Integer) Boolean)
 (@def zap-to-char (arg: Integer char: Integer &optional interactive: Bool) Nil)
 (@def kill-line (&optional arg: Integer?) Nil)
 (@def kill-whole-line (&optional arg: Integer?) Nil)
 (@def forward-visible-line (arg: Integer) Nil)
 (@def end-of-visible-line () Nil)
 (@def kill-current-buffer () Nil)
 (@def insert-buffer (buffer: Buffer|String) Nil)
 (@def append-to-buffer (buffer: Buffer|String start: IntOrMarker end: IntOrMarker) Nil)
 (@def prepend-to-buffer (buffer: Buffer|String start: IntOrMarker end: IntOrMarker) Nil)
 (@def copy-to-buffer (buffer: Buffer|String start: IntOrMarker end: IntOrMarker) Nil)
 (@def mark (&optional force: Bool) Integer?)
 (@def deactivate-mark (&optional force: Bool) Nil)
 (@def activate-mark (&optional no-tmm: Bool) Nil)
 (@def set-mark (pos: Integer?) Nil)
 (@check save-mark-and-excursion ($body))
 (@def use-region-beginning () Integer?)
 (@def use-region-end () Integer?)
 (@def use-region-noncontiguous-p () Boolean)
 (@def use-region-p () Boolean)
 (@def region-active-p () Boolean)
 (@def region-bounds () List<Cons<Integer~Integer>>)
 (@def region-noncontiguous-p () Boolean)
 (@def cursor-face-highlight-mode (&optional arg: Bool) Boolean)
 (@def pop-to-mark-command () Nil)
 (@def push-mark-command (arg: Any &optional nomsg: Bool) Nil)
 (@def set-mark-command (arg: Any) Nil)
 (@def push-mark (&optional location: Integer? nomsg: Bool activate: Bool) Nil)
 (@def pop-mark () Nil)
 (@def exchange-point-and-mark (&optional arg: Any) Nil)
 (@def handle-shift-selection () Nil)
 (@def transient-mark-mode (&optional arg: Bool) Boolean)
 (@def indent-tabs-mode (&optional arg: Bool) Boolean)
 (@def pop-global-mark () Nil)
 (@def next-line (&optional arg: Integer? try-vscroll: Bool) Nil)
 (@def previous-line (&optional arg: Integer? try-vscroll: Bool) Nil)
 (@def default-font-height () Integer)
 (@def default-font-width () Integer)
 (@def default-line-height () Integer)
 (@def window-screen-lines () Number)
 (@def line-move-partial (arg: Integer noerror: Bool &optional to-end: Any) Boolean)
 (@def line-move (arg: Integer &optional noerror: Bool to-end: Any try-vscroll: Bool) Any)
 (@def line-move-visual (arg: Integer &optional noerror: Bool) Any)
 (@def line-move-1 (arg: Integer &optional noerror: Bool to-end: Any) Boolean)
 (@def line-move-finish (column: Number opoint: Integer forward: Bool &optional not-ipmh: Bool) Nil)
 (@def line-move-to-column (col: Integer) Nil)
 (@def move-end-of-line (arg: Integer) Nil)
 (@def move-beginning-of-line (arg: Integer) Nil)
 (@def set-goal-column (arg: Any) Nil)
)

;;; ============================================================
;;; Editing based on visual lines, as opposed to logical lines.

(et-declare
 (@def end-of-visual-line (&optional n: Integer?) Integer)
 (@def beginning-of-visual-line (&optional n: Integer?) Integer)
 (@def kill-visual-line (&optional arg: Integer?) Nil)
 (@def next-logical-line (&optional arg: Integer? try-vscroll: Bool) Nil)
 (@def previous-logical-line (&optional arg: Integer? try-vscroll: Bool) Nil)
 (@def visual-line-mode (&optional arg: Bool) Boolean)
 (@def turn-on-visual-line-mode () Boolean)
 (@def transpose-chars (arg: Integer) Any)
 (@def transpose-words (arg: Integer) Any)
 (@def transpose-sexps-default-function (arg: Integer) Cons<Integer~Integer>)
 (@def transpose-sexps (arg: Integer &optional interactive: Bool) Any)
 (@def transpose-lines (arg: Integer) Any)
 (@def transpose-subr (mover: fn1<Integer> arg: Integer &optional special: Any) Any)
 (@def transpose-subr-1 (pos1: Cons<Integer~Integer> pos2: Cons<Integer~Integer>) Nil)
 (@def backward-word (&optional arg: Integer?) Any)
 (@def mark-word (&optional arg: Any allow-extend: Bool) Nil)
 (@def kill-word (arg: Integer) Nil)
 (@def backward-kill-word (arg: Integer) Nil)
 (@def current-word (&optional strict: Bool really-word: Bool) String?)
 (@def forward-unix-word (n: Integer &optional delim: String?) Nil)
 (@def unix-word-rubout (arg: Integer) Nil)
 (@def unix-filename-rubout (arg: Integer) Nil)
 (@def do-auto-fill () Boolean)
 (@def default-indent-new-line (&optional soft: Bool force: Bool) Any)
 (@def internal-auto-fill () Nil)
 (@def auto-fill-mode (&optional arg: Bool) Boolean)
 (@def auto-fill-function () Nil)
 (@def turn-on-auto-fill () Boolean)
 (@def turn-off-auto-fill () Boolean)
 (@def set-fill-column (arg: Any) Integer)
 (@def set-selective-display (arg: Any) String)
 (@def toggle-truncate-lines (&optional arg: Any) String)
 (@def toggle-word-wrap (&optional arg: Any) String)
 (@def overwrite-mode (&optional arg: Bool) Boolean)
 (@def binary-overwrite-mode (&optional arg: Bool) Boolean)
 (@def line-number-mode (&optional arg: Bool) Boolean)
 (@def column-number-mode (&optional arg: Bool) Boolean)
 (@def size-indication-mode (&optional arg: Bool) Boolean)
 (@def mode-line-invisible-mode (&optional arg: Bool) Boolean)
 (@def auto-save-mode (&optional arg: Bool) Boolean)
 (@def blink-matching-check-mismatch (start: Integer? end: Integer) Boolean)
 (@def blink-matching-open () Any)
 (@def blink-paren-open-paren-line-string (pos: Integer) String)
 (@def blink-paren-post-self-insert-function () Nil)
 (@def keyboard-quit () Never)
 (@def keyboard-escape-quit () Any)
 (@def play-sound-file (file: String &optional volume: Number? device: String?) Any)
 (@def rfc822-goto-eoh () Integer?)
 (@def compose-mail (&optional to: String? subject: String? other-headers: Alist<String~String>? continue: Bool switch-function: fn1<Buffer>? yank-action: Any send-actions: &List? return-action: Any) Any)
 (@def compose-mail-other-window (&optional to: String? subject: String? other-headers: Alist<String~String>? continue: Bool yank-action: Any send-actions: &List? return-action: Any) Any)
 (@def compose-mail-other-frame (&optional to: String? subject: String? other-headers: Alist<String~String>? continue: Bool yank-action: Any send-actions: &List? return-action: Any) Any)
 (@def set-variable (variable: NonNilSymbol value: Any &optional make-local: Bool) Nil)
 (@def delete-completion-window () Nil)
 (@def first-completion () Nil)
 (@def last-completion () Nil)
 (@def previous-column-completion (n: Integer) Nil)
 (@def next-column-completion (n: Integer) Nil)
 (@def previous-line-completion (&optional n: Integer?) Nil)
 (@def next-line-completion (&optional n: Integer?) Nil)
 (@def next-completion (&optional n: Integer?) Nil)
 (@def previous-completion (&optional n: Integer?) Nil)
 (@def completion-list-candidate-at-point (&optional pt: Integer?) List?)
 (@def choose-completion (&optional event: Any no-exit: Bool no-quit: Bool) Any)
 (@def choose-completion-guess-base-position (string: String) Integer)
 (@def choose-completion-string (choice: String &optional buffer: Buffer? base-position: &List? insert-function: Any) Any)
 (@def completion-list-mode () Nil)
 (@def completion-list-mode-finish () Nil)
 (@def completion-setup-function () Nil)
 (@def switch-to-completions () Nil)
 (@def read-expression-switch-to-completions () Nil)
 (@def switch-to-minibuffer () Nil)
)

;;; ============================================================
;;; Support keyboard commands to turn on various modifiers.

(et-declare
 (@def event-apply-alt-modifier (ignore-prompt: Any) Vector)
 (@def event-apply-super-modifier (ignore-prompt: Any) Vector)
 (@def event-apply-hyper-modifier (ignore-prompt: Any) Vector)
 (@def event-apply-shift-modifier (ignore-prompt: Any) Vector)
 (@def event-apply-control-modifier (ignore-prompt: Any) Vector)
 (@def event-apply-meta-modifier (ignore-prompt: Any) Vector)
 (@def event-apply-modifier (event: Any symbol: NonNilSymbol lshiftby: Integer prefix: String) Any)
 (@def clone-process (process: Process &optional newname: String?) Process?)
 (@def clone-buffer (&optional newname: String? display-flag: Bool) Buffer)
 (@def clone-indirect-buffer (newname: String? display-flag: Bool &optional norecord: Bool) Buffer)
 (@def clone-indirect-buffer-other-window (newname: String? display-flag: Bool &optional norecord: Bool) Any)
)

;;; ============================================================
;;; Handling of Backspace and Delete keys.

(et-declare
 (@def normal-erase-is-backspace-setup-frame (&optional frame: Frame?) Nil)
 (@def normal-erase-is-backspace-mode (&optional arg: Bool) Boolean)
 (@def read-only-mode (&optional arg: Bool) Boolean)
 (@def visible-mode (&optional arg: Bool) Boolean)
 (@def messages-buffer-mode () Nil)
 (@def messages-buffer () Buffer)
 (@def bad-package-check (package: NonNilSymbol|String) Any)
)

;;; ============================================================
;;; Generic dispatcher commands

(et-declare
 ;; This macro generates a defcustom and a defun from an unquoted
 ;; symbol name, and does not evaluate a body in the caller's
 ;; environment. There is no checker shortcut for a definition-
 ;; generating macro whose expansion introduces new top-level bindings.
 (@check define-alternatives ($todo))
)

;;; ============================================================
;;; Functions for changing capitalization that Do What I Mean

(et-declare
 (@def upcase-dwim (arg: Integer) Nil)
 (@def downcase-dwim (arg: Integer) Nil)
 (@def capitalize-dwim (arg: Integer) Nil)
)

;;; ============================================================

(et-declare
 (@def get-scratch-buffer-create () Buffer)
 (@def scratch-buffer () Any)
 (@def string-empty-p (string: String) Boolean)
 (@def read-signal-name () Integer|NonNilSymbol)
 (@def lax-plist-get (plist: &List prop: Any) Any)
 (@def lax-plist-put (plist: List prop: Any val: Any) List)
 (@def analyze-text-conversion () Nil)
)

;;; ============================================================
