;; Type definitions for lisp/emacs-lisp/seq.el.

;;; Helpers

(defun et--seq-element-type (sequence)
  "Return the element type of SEQUENCE."
  (or (et-checker-infer sequence [T] ListR<T> T)
      (et-checker-infer sequence [T] VectorR<T> T)
      (and (et-subtype? sequence (et String)) (et Integer))
      (et-any)))

(defun et--seq-literal-symbols (type)
  "Return literal symbols represented by TYPE, or nil if not all symbols."
  (let ((expanded (et-expand-all-aliases (et--remove-type-binds type))))
    (cl-loop for case in (et-type-cases expanded)
             for val = (et-type-case-value case)
             if (and (et-datatype-p val)
                     (eq (et-datatype-name val) 'Literal)
                     (symbolp (car (et-datatype-args val))))
             collect (car (et-datatype-args val))
             else return nil)))

(defun et--seq-into-type (elem type)
  "Return a sequence of ELEM requested by literal TYPE."
  (let ((symbols (et--seq-literal-symbols type)))
    (if symbols
        (apply #'et--or
               (cl-loop for sym in symbols
                        collect
                        (pcase sym
                          ('list (et-alias 'ListFresh elem))
                          ('vector (et-dt 'VectorFresh elem))
                          ('string (et String))
                          (_ (et-any)))))
      (et-any))))

(et-define-op seq-element (sequence)
  (et--seq-element-type sequence))

(et-define-op seq-into (elem type)
  (et--seq-into-type elem type))

(et-declare
 (@alias Sequence [E] (or String ListR<E> VectorR<E>))
 (@alias SequenceR [E]
         (or (and String (set E Integer))
             ListR<E>
             VectorR<E>)))


;;; Basic access

(et-declare
 (@function seq-elt (sequence n)
            (@generics [S E])
            (sequence S&SequenceR<E>) (n Integer)
            (@return E|Nil))
 (@function seq-first (sequence)
            (@generics [E])
            (sequence SequenceR<E>)
            (@return E|Nil))
 (@function seq-random-elt (sequence)
            (@generics [E])
            (sequence SequenceR<E>)
            (@return E))
 (@function seq-rest (sequence)
            (@generics [S E])
            (sequence S&SequenceR<E>)
            (@return S))
 (@function seq-length (sequence)
            (sequence SequenceR<Any>) (@return Integer))
 (@function seq-empty-p (sequence)
            (sequence SequenceR<Any>) (@return Boolean)))

;;; Predicates and search

(et-declare
 (@function seq-some (pred sequence)
            (@generics [E R])
            (pred (Function (Args E) R))
            (sequence SequenceR<E>)
            (@return R|Nil))
 (@function seq-every-p (pred sequence)
            (@generics [E])
            (pred (Function (Args E) Any))
            (sequence SequenceR<E>)
            (@return Boolean))
 (@function seq-count (pred sequence)
            (@generics [E])
            (pred (Function (Args E) Any))
            (sequence SequenceR<E>)
            (@return Integer))
 (@function seq-find (pred sequence &optional default)
            (@generics [E D])
            (pred (Function (Args E) Any))
            (sequence SequenceR<E>) (default D)
            (@return (or E D Nil)))
 (@function seq-position (sequence elt &optional testfn)
            (@generics [E])
            (sequence SequenceR<E>) (elt Any)
            (testfn (or Nil (Function (Args E Any) Any)))
            (@return Integer|Nil))
 (@function seq-positions (sequence elt &optional testfn)
            (@generics [E])
            (sequence SequenceR<E>) (elt Any)
            (testfn (or Nil (Function (Args E Any) Any)))
            (@return ListFresh<Integer>))
 (@function seq-contains (sequence elt &optional testfn)
            (@generics [E])
            (sequence SequenceR<E>) (elt Any)
            (testfn (or Nil (Function (Args E Any) Any)))
            (@return (or E Nil)))
 (@function seq-contains-p (sequence elt &optional testfn)
            (@generics [E])
            (sequence SequenceR<E>) (elt Any)
            (testfn (or Nil (Function (Args E Any) Any)))
            (@return Boolean)))

;;; Mapping and iteration

(et-declare
 (@function seq-map (function sequence)
            (@generics [E R])
            (function (Function (Args E) R))
            (sequence SequenceR<E>)
            (@return ListFresh<R>))
 (@function seq-map-indexed (function sequence)
            (@generics [E R])
            (function (Function (Args E Integer) R))
            (sequence SequenceR<E>)
            (@return ListFresh<R>))
 (@function seq-keep (function sequence)
            (@generics [E R])
            (function (Function (Args E) R))
            (sequence SequenceR<E>)
            (@return ListFresh<R>))
 (@function seq-mapn (function sequence &rest sequences)
            (@generics [T R])
            (function (Function (Args T) R))
            (sequence SequenceR<T>) (sequences ListR<SequenceR<T>>)
            (@return ListFresh<R>))
 (@function seq-mapcat (function sequence &optional type)
            (@generics [E R Y])
            (function (Function (Args E) Sequence<R>))
            (sequence SequenceR<E>) (type Y)
            (@return (seq-into R Y)))
 (@function seq-do (function sequence)
            (@generics [S E])
            (function (Function (Args E) Any))
            (sequence S&SequenceR<E>)
            (@return S))
 (@function seq-each (function sequence)
            (@generics [S E])
            (function (Function (Args E) Any))
            (sequence S&SequenceR<E>)
            (@return S))
 (@function seq-do-indexed (function sequence)
            (@generics [E])
            (function (Function (Args E Integer) Any))
            (sequence SequenceR<E>)
            (@return Nil)))

;;; Filtering and set-like operations

(et-declare
 (@function seq-filter (pred sequence)
            (@generics [E])
            (pred (Function (Args E) Any))
            (sequence SequenceR<E>)
            (@return (ListFresh E)))
 (@function seq-remove (pred sequence)
            (@generics [E])
            (pred (Function (Args E) Any))
            (sequence SequenceR<E>)
            (@return (ListFresh E)))
 (@function seq-uniq (sequence &optional testfn)
            (@generics [E])
            (sequence SequenceR<E>)
            (testfn (or Nil (Function (Args E E) Any)))
            (@return (ListFresh E)))
 (@function seq-union (sequence1 sequence2 &optional testfn)
            (@generics [E1 E2])
            (sequence1 SequenceR<E1>) (sequence2 SequenceR<E2>)
            (testfn (or Nil (Function (Args E1 E2) Any)))
            (@return (ListFresh (or E1 E2))))
 (@function seq-intersection (sequence1 sequence2 &optional testfn)
            (@generics [E1 E2])
            (sequence1 SequenceR<E1>) (sequence2 SequenceR<E2>)
            (testfn (or Nil (Function (Args E1 E2) Any)))
            (@return (ListFresh (and E1 E2))))
 (@function seq-difference (sequence1 sequence2 &optional testfn)
            (@generics [E1 E2])
            (sequence1 SequenceR<E1>) (sequence2 SequenceR<E2>)
            (testfn (or Nil (Function (Args E1 E2) Any)))
            (@return (ListFresh E1)))
 (@function seq-set-equal-p (sequence1 sequence2 &optional testfn)
            (@generics [E1 E2])
            (sequence1 SequenceR<E1>) (sequence2 SequenceR<E2>)
            (testfn (or Nil (Function (Args E1 E2) Any)))
            (@return Boolean)))

;;; Sub-sequences and ordering

(et-declare
 (@function seq-take (sequence n)
            (@generics [S E])
            (sequence S&SequenceR<E>) (n Integer)
            (@return S))
 (@function seq-drop (sequence n)
            (@generics [S E])
            (sequence S&SequenceR<E>) (n Integer)
            (@return S))
 (@function seq-take-while (pred sequence)
            (@generics [S E])
            (pred (Function (Args E) Any))
            (sequence S&SequenceR<E>)
            (@return S))
 (@function seq-drop-while (pred sequence)
            (@generics [S E])
            (pred (Function (Args E) Any))
            (sequence S&SequenceR<E>)
            (@return S))
 (@function seq-subseq (sequence start &optional end)
            (@generics [S E])
            (sequence S&SequenceR<E>) (start Integer) (end Integer|Nil)
            (@return S))
 (@function seq-copy (sequence)
            (@generics [S E])
            (sequence S&SequenceR<E>)
            (@return (eval et--freshen-type S)))
 (@function seq-reverse (sequence)
            (@generics [S E])
            (sequence S&SequenceR<E>)
            (@return S))
 (@function seq-sort (pred sequence)
            (@generics [S E])
            (pred (Function (Args E E) Any))
            (sequence S&SequenceR<E>)
            (@return S))
 (@function seq-sort-by (function pred sequence)
            (@generics [S E K])
            (function (Function (Args E) K))
            (pred (Function (Args K K) Any))
            (sequence S&SequenceR<E>)
            (@return S)))

;;; Construction and grouping

(et-declare
 (@function seq-into (sequence type)
            (@generics [E Y])
            (sequence SequenceR<E>) (type Y)
            (@return (seq-into E Y)))
 (@function seq-into-sequence (sequence)
            (@generics [S E])
            (sequence S&SequenceR<E>)
            (@return S))
 (@function seq-concatenate (type &rest sequences)
            (@generics [E Y])
            (type Y) (sequences ListR<SequenceR<E>>)
            (@return (seq-into E Y)))
 (@function seq-partition (sequence n)
            (@generics [S E])
            (sequence S&SequenceR<E>) (n Integer)
            (@return (ListFresh S)))
 (@function seq-split (sequence length)
            (@generics [S E])
            (sequence S&SequenceR<E>) (length Integer)
            (@return (ListFresh S)))
 (@function seq-group-by (function sequence)
            (@generics [E K])
            (function (Function (Args E) K))
            (sequence SequenceR<E>)
            (@return (AList K E)))
 (@function seq-remove-at-position (sequence n)
            (@generics [S E])
            (sequence S&SequenceR<E>) (n Integer)
            (@return S)))

;;; Numeric extrema

(et-declare
 (@function seq-min (sequence)
            (@generics [S])
            (sequence S&SequenceR<NumOrMarker>)
            (@return Number))
 (@function seq-max (sequence)
            (@generics [S])
            (sequence S&SequenceR<NumOrMarker>)
            (@return Number)))

;;; Macros

(et-declare
 (@macro seq-let :expand t)
 (@macro seq-setq :expand t)
 (@macro seq-doseq :expand t))

;;; seq.el ends here
